@echo off
REM ============================================================
REM  ai-news-cards : auto-upload to iwinv server (replaces GitHub Pages push)
REM  Run daily by Windows Task Scheduler.
REM  Uploads the public\ folder (generated by Claude) to the server web root via scp.
REM ============================================================

cd /d "%~dp0"

REM ---- settings (edit these 4 lines if needed) ----
set "IWINV_HOST=49.247.137.87"
set "IWINV_USER=root"
set "IWINV_PATH=/var/www/ai-news-cards"
set "SSH_KEY=%USERPROFILE%\.ssh\iwinv_deploy"
REM ---------------------------------------------------

if not exist "logs" mkdir "logs"
set "LOG=logs\deploy_iwinv.log"
echo. >> "%LOG%"
echo ===== %DATE% %TIME% : deploy_to_iwinv start ===== >> "%LOG%"

if not exist "%SSH_KEY%" (
  echo SSH key not found at %SSH_KEY% >> "%LOG%"
  echo SSH key not found at %SSH_KEY%
  echo   Run the SSH key setup step first - see IWINV_SETUP.md section 7.
  goto :eof
)

echo uploading public\ to %IWINV_USER%@%IWINV_HOST%:%IWINV_PATH% >> "%LOG%"

scp -i "%SSH_KEY%" -o StrictHostKeyChecking=no -r "public\*" "%IWINV_USER%@%IWINV_HOST%:%IWINV_PATH%/" >> "%LOG%" 2>&1

if %errorlevel%==0 (
  echo upload OK - https://ai-news.wiselab.kr >> "%LOG%"
  echo upload OK - https://ai-news.wiselab.kr
) else (
  echo UPLOAD FAILED - see %LOG% >> "%LOG%"
  echo UPLOAD FAILED - see %LOG%
)
echo ===== done ===== >> "%LOG%"
